### ISSUE TITLE
check dates

### ISSUE THREAD

**Issue by abibard** [ropensci/comtradr#63] opened 2023-08-22 15:25 UTC
Hi, when I try to check dates betwee June 2022 and December 2022 , monthly it returns an error message "! Cannot get more than a single year's worth of monthly data in a single query." Actually it is 6 months data..

`# check dates
dates<-check_date(2022-06,2022-12,"M")
`
```
Error in `check_date()`:
! Cannot get more than a single year's worth of monthly data in a single query.
```
Any idea?

**Comment by abibard** [comment] 2023-08-22 15:34
Sorry I found my error. Quotes were needed... (unlike yearly request..)
`dates<-check_date("2022-06","2022-12","M")`

Any way to extract more than 1 year of monthly data? I granted a premium access in this purpose... Thanks!

**Comment by datapumpernickel** [comment] 2023-08-22 18:45
Hi @abibard!

Thanks for your feedback. I think it won`t be possible to implement the possibility to pass month as integers like you did on your first function call. In any case it would have to be something like 201212 without the `-` operator in between. But I am glad you figured it out! 

Is there something you suggest we should change in the documentation to make it more clear? 

Besides of that we have not implemented any of the premium functions yet, because we wanted to focus on the public version first. But I hope we will get to that at some point. 
Probably you can pass in more than 12 month in the bulk api. 
See here for some python examples: https://github.com/uncomtrade/comtradeapicall/blob/main/tests/example%20calling%20functions%20-%20notebook.ipynb 

Feel free to give us feedback, we are happy to see people putting the package to use!

**Comment by datapumpernickel** [comment] 2023-10-15 07:39
Closing, as the issue is resolved.

**Closed by datapumpernickel** 2023-10-15 07:39 UTC
